<?php
namespace jc\test\unit\testcase\jc\lang;

use jc\lang\Object ;

/**
 * Test class for Object.
 * Generated by PHPUnit on 2011-08-15 at 12:15:25.
 */
class ObjectTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Object
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ObjectTest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testApplication().
     */
    public function testApplication()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetApplication().
     */
    public function testSetApplication()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCreateInstance().
     */
    public function testCreateInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSingleton().
     */
    public function testSingleton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetSingleton().
     */
    public function testSetSingleton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testFindApplicationOnCallStack().
     */
    public function testFindApplicationOnCallStack()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetFlyweight().
     */
    public function testSetFlyweight()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testFlyweight().
     */
    public function testFlyweight()
    {
        $aIns1 = MockFlyweightClass::flyweight(array(1,2)) ;
        $aIns2 = MockFlyweightClass::flyweight(3) ;
        
        $this->assertFalse($aIns1===$aIns2) ;
        $this->assertEquals($aIns1->arrParams,array(1,2)) ;
        $this->assertEquals($aIns2->arrParams,array(3)) ;
        
        // 使用 数组 或 对象 做为享元的键
        $aIns3 = MockFlyweightClass::flyweight(array(array(1,2),3)) ;
        $aIns4 = MockFlyweightClass::flyweight(array(array(4,5),3)) ;
        $this->assertFalse($aIns3===$aIns4) ;
        
        $aIns5 = MockFlyweightClass::flyweight(array($aIns3,3)) ;
        $aIns6 = MockFlyweightClass::flyweight(array($aIns4,3)) ;
        $this->assertFalse($aIns5===$aIns6) ;
        
    }
}

class MockFlyweightClass extends Object
{
	public function __construct()
	{
		$this->arrParams = func_get_args() ;
	}
	
	public $arrParams ;
}
?>
