<?php
namespace jc\test\unit\testcase\jc\aop;

use jc\pattern\composite\IContainer;

/**
 * Test class for Aspect.
 * Generated by PHPUnit on 2011-08-17 at 16:46:29.
 */
class Aspect extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Aspect
     */
    protected $aAspect;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->aAspect = new \jc\aop\Aspect;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testPointcuts().
     */
    public function testPointcuts()
    {
		$this->assertTrue(  $this->aAspect->pointcuts() instanceof IContainer ) ;
    }
}
?>
