<?php
namespace jc\test\unit\testcase\jc\lang\aop;

use jc\lang\aop\AOP ;
use jc\pattern\composite\IContainer;

/**
 * Test class for AOP.
 * Generated by PHPUnit on 2011-08-17 at 16:46:24.
 */
class AOPTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AOP
     */
    protected $aAOP;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->aAOP = new AOP;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testAspects().
     */
    public function testAspects()
    {
		$this->assertTrue( $this->aAOP->aspects() instanceof IContainer ) ;
    }
}
?>
