<?php
namespace jc\test\unit\testcase\jc\lang\aop;

use jc\lang\aop\Pointcut ;
use jc\pattern\composite\IContainer;

/**
 * Test class for Pointcut.
 * Generated by PHPUnit on 2011-08-17 at 16:46:45.
 */
class PointcutTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Pointcut
     */
    protected $aPointcut ;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->aPointcut = new Pointcut;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testJointPoints().
     */
    public function testJointPoints()
    {
        $this->assertTrue( $this->aPointcut->jointPoints() instanceof IContainer ) ;
    }

    /**
     * @todo Implement testAdvices().
     */
    public function testAdvices()
    {
        $this->assertTrue( $this->aPointcut->advices() instanceof IContainer ) ;
    }
}
?>
