<?php
namespace jc\test\unit\testcase\jc\compile\object;

use jc\compile\ClassCompileException;
use jc\compile\object\Token;

/**
 * Test class for NamespaceDeclare.
 * Generated by PHPUnit on 2011-08-18 at 15:14:35.
 */
class NamespaceDeclare extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @see self::testName()
     */
    public function testAddNameToken()
    {
        $this->testName() ;
    }

    /**
     * @todo Implement testName().
     */
    public function testName()
    {
    	// 错误的构造函数参数
    	try{
	        $aNamespaceDeclare = new \jc\compile\object\NamespaceDeclare(
	        	new Token(T_CLASS, 'namespace', 123)
	        ) ;
    	}
    	catch (ClassCompileException $e)
    	{}
    	$this->assertNotNull($e) ;
    	
    	// 正确的构造函数参数
        $aNamespaceDeclare = new \jc\compile\object\NamespaceDeclare(
        	new Token(T_NAMESPACE, 'namespace', 123)
        ) ;
        
        // 错误的 addNameToken() 参数
    	try{
	        $aNamespaceDeclare->addNameToken(new Token(T_CLASS, 'namespace', 123)) ;
    	}
    	catch (ClassCompileException $e)
    	{}
    	$this->assertNotNull($e) ;
    	
        // 正确的 addNameToken() 参数
	    $aNamespaceDeclare->addNameToken(new Token(T_STRING, 'some', 123)) ;
	    $aNamespaceDeclare->addNameToken(new Token(T_STRING, 'package', 133)) ;
	    $aNamespaceDeclare->addNameToken(new Token(T_STRING, 'name', 143)) ;
	    
	    $this->assertEquals($aNamespaceDeclare->name(),'some\\package\\name') ;
    }
}
?>
