<?php
namespace jc\test\unit\testcase\jc\compile\object;

use jc\compile\object\FunctionDefine;
use jc\compile\object\ClassDefine;
use jc\compile\object\NamespaceDeclare;
use jc\compile\object\TokenPool;
use jc\compile\object\Token ;

/**
 * Test class for jc\compile\object\Token.
 * Generated by PHPUnit on 2011-08-19 at 18:25:58.
 */
class TokenTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @see self::testTokenType()
     */
    public function testSetTokenType()
    {
        $this->testTokenType() ;
    }

    /**
     * @todo Implement testTokenType().
     */
    public function testTokenType()
    {
        $aToken = new Token(T_STRING,'ooxx',100) ;
        $this->assertEquals($aToken->tokenType(), T_STRING) ;
        
        $aToken->setTokenType(T_SWITCH) ;
        $this->assertEquals($aToken->tokenType(), T_SWITCH) ;
        
        // 特殊的类型
        $aToken = new Token(T_STRING,'{',100) ;
        $this->assertEquals($aToken->tokenType(), Token::T_BRACE_OPEN) ;
        $this->assertEquals($aToken->tokenType(true), T_STRING) ;
        
        $aToken = new Token(T_STRING,'}',100) ;
        $this->assertEquals($aToken->tokenType(), Token::T_BRACE_CLOSE) ;
        $this->assertEquals($aToken->tokenType(true), T_STRING) ;
        
        $aToken = new Token(T_STRING,'[',100) ;
        $this->assertEquals($aToken->tokenType(), Token::T_BRACE_SQUARE_OPEN) ;
        $this->assertEquals($aToken->tokenType(true), T_STRING) ;
        
        $aToken = new Token(T_STRING,']',100) ;
        $this->assertEquals($aToken->tokenType(), Token::T_BRACE_SQUARE_CLOSE) ;
        $this->assertEquals($aToken->tokenType(true), T_STRING) ;
        
        $aToken = new Token(T_STRING,'(',100) ;
        $this->assertEquals($aToken->tokenType(), Token::T_BRACE_ROUND_OPEN) ;
        $this->assertEquals($aToken->tokenType(true), T_STRING) ;
        
        $aToken = new Token(T_STRING,')',100) ;
        $this->assertEquals($aToken->tokenType(), Token::T_BRACE_ROUND_CLOSE) ;
        $this->assertEquals($aToken->tokenType(true), T_STRING) ;
        
        $aToken = new Token(T_STRING,';',100) ;
        $this->assertEquals($aToken->tokenType(), Token::T_SEMICOLON) ;
        $this->assertEquals($aToken->tokenType(true), T_STRING) ;
        
    }

    /**
     * @todo Implement testTokenTypeName().
     */
    public function testTokenTypeName()
    {
        $this->assertEquals(
        	'T_STRING', Token::createInstance(array(T_STRING,'ooxx',100))->tokenTypeName()
        ) ;
        
        $this->assertEquals(
        	'T_SWITCH', Token::createInstance(array(T_SWITCH,'switch',100))->tokenTypeName()
        ) ;
        
        $this->assertEquals(
        	'T_ARRAY', Token::createInstance(array(T_ARRAY,'array',100))->tokenTypeName()
        ) ;
        
        $this->assertEquals(
        	'T_AS', Token::createInstance(array(T_AS,'as',100))->tokenTypeName()
        ) ;
        
        // ...
        
        // 特殊的类型
        $this->assertEquals(
        	'Token::T_BRACE_SQUARE_CLOSE', Token::createInstance(array(Token::T_BRACE_SQUARE_CLOSE,']',100))->tokenTypeName()
        ) ;
        $this->assertEquals(
        	'Token::T_BRACE_ROUND_OPEN', Token::createInstance(array(Token::T_BRACE_ROUND_OPEN,'(',100))->tokenTypeName()
        ) ;
        $this->assertEquals(
        	'Token::T_SEMICOLON', Token::createInstance(array(Token::T_SEMICOLON,';',100))->tokenTypeName()
        ) ;
    }

    /**
     * @todo Implement testObjectPool().
     */
    public function testObjectPool()
    {
    	$aTokenPool = new TokenPool() ;
    	$aToken = new Token(Token::T_BRACE_SQUARE_CLOSE,']',100) ;
    	
    	$aTokenPool->add($aToken,null,true) ;
    	$this->assertTrue($aTokenPool===$aToken->objectPool()) ;
    }

    /**
     * @see self::testBelongsNamespace()
     */
    public function testSetBelongsNamespace()
    {
        $this->testBelongsNamespace() ;
    }

    /**
     * @todo Implement testBelongsNamespace().
     */
    public function testBelongsNamespace()
    {
    	$aToken = new Token(T_BREAK,'break',150) ;
    	$this->assertNull($aToken->belongsNamespace()) ;
    	
    	$aNamespace = new NamespaceDeclare(new Token(T_NAMESPACE, 'namespace', 100)) ;
    	$aToken->setBelongsNamespace($aNamespace) ;
    	$this->assertTrue($aToken->belongsNamespace()===$aNamespace) ;
    }

    /**
     * @see self::testBelongsClass()
     */
    public function testSetBelongsClass()
    {
        $this->testBelongsClass() ;
    }

    /**
     * @todo Implement testBelongsClass().
     */
    public function testBelongsClass()
    {
    	$aToken = new Token(T_BREAK,'break',150) ;
    	$this->assertNull($aToken->belongsClass()) ;
    	
    	$aClassDefine = new ClassDefine(new Token(T_CLASS, 'class', 100)) ;
    	$aToken->setBelongsClass($aClassDefine) ;
    	$this->assertTrue($aToken->belongsClass()===$aClassDefine) ;
    }

    /**
     * @see self::testBelongsFunction()
     */
    public function testSetBelongsFunction()
    {
        $this->testBelongsFunction() ;
    }

    /**
     * @todo Implement testBelongsFunction().
     */
    public function testBelongsFunction()
    {
    	$aToken = new Token(T_BREAK,'break',150) ;
    	$this->assertNull($aToken->belongsFunction()) ;
    	
    	$aFunctionDefine = new FunctionDefine(new Token(T_FUNCTION, 'function', 100)) ;
    	$aToken->setBelongsFunction($aFunctionDefine) ;
    	$this->assertTrue($aToken->belongsFunction()===$aFunctionDefine) ;
    }

    /**
     * @todo Implement testBelongsSignature().
     */
    public function testBelongsSignature()
    {
    	$aToken = new Token(T_BREAK,'break',150) ;
    	$this->assertTrue($aToken->belongsSignature()==='') ;
    	
    	// 设置命名空间
    	$aNamespace = new NamespaceDeclare(new Token(T_NAMESPACE, 'namespace', 100)) ;
    	$aNamespace->addNameToken(new Token(T_STRING, 'package', 100)) ;
    	$aNamespace->addNameToken(new Token(T_STRING, 'name', 100)) ;
    	$aNamespace->addNameToken(new Token(T_STRING, 'abc', 100)) ;
    	$aToken->setBelongsNamespace($aNamespace) ;
    	$this->assertEquals($aToken->belongsSignature(),"[package\\name\\abc\\]") ;
    	
    	// 设置函数名
    	$aFunctionDefine = new FunctionDefine(new Token(T_FUNCTION, 'function', 100)) ;
    	$aFunctionDefine->setNameToken(new Token(T_STRING, 'functionNameAbc', 100)) ;
    	$aToken->setBelongsFunction($aFunctionDefine) ;
    	$this->assertEquals($aToken->belongsSignature(),"[package\\name\\abc\\functionNameAbc()]") ;
    	
    	// 设置类名
    	$aClassDefine = new ClassDefine(new Token(T_CLASS, 'class', 100)) ;
    	$aClassDefine->setNameToken(new Token(T_STRING, 'ClassNameAbc', 100)) ;
    	$aToken->setBelongsClass($aClassDefine) ;
    	$this->assertEquals($aToken->belongsSignature(),"[package\\name\\abc\\ClassNameAbc::functionNameAbc()]") ;
    	
    }
}
?>
